---
title: "Jc Transportes - Tratamento dos bancos de dados"
output: html_notebook
---

```{r, warning = FALSE}
library(dplyr)
library(here)
library(data.table)
library(readxl)  
library(tools)   
```

```{r, warning = FALSE}
# Lendo arquivos CSV 
csv_files <- list.files(here("Dados"), pattern = "\\.csv$", full.names = TRUE)

csv_data <- lapply(csv_files, read.csv2, encoding = "latin1")

names(csv_data) <- csv_files %>%
  basename() %>%
  file_path_sans_ext()

# Read XLSX
xlsx_files <- list.files(here("Dados"), pattern = "\\.xls[x]?$", full.names = TRUE)

xlsx_data <- lapply(xlsx_files, read_excel)
names(xlsx_data) <- xlsx_files %>%
  basename() %>%
  file_path_sans_ext()

# Optional: Combine all into one list
all_data <- c(csv_data, xlsx_data)

#Removendo demais variáveis
rm(csv_data, csv_files, xlsx_data, xlsx_files)
```

```{r}
#Corrigir os arquivos csv:
all_data <- lapply(all_data, function(df) {
  if (ncol(df) == 1) {
    raw_text <- df[[1]]
    parsed_df <- read.csv(text = raw_text, header = TRUE, stringsAsFactors = FALSE)
    return(parsed_df)
  } else {
    return(df)
  }
})
```

## Base de Municípios e Anos

```{r}
#Base dos municípios
df <- all_data$RELATORIO_DTB_BRASIL_2024_MUNICIPIOS %>% 
  data.table()

#Ajustando a base
header_df <- as.character(df[6, ])
df <- df[7:nrow(df), ]
colnames(df) <- header_df

df <- df %>% 
  select(`Código Município Completo`, Nome_Município) %>% 
  rename(i_CodIBGE = `Código Município Completo`, 
         i2_Nome_Municipio = Nome_Município)

df <- expand.grid(
  i_CodIBGE = unique(df$i_CodIBGE),
  t_Ano = 2005:2024,
  stringsAsFactors = FALSE
) %>%
  merge(df, by = "i_CodIBGE", all = TRUE) %>%
  data.table(key = c("i_CodIBGE", "t_Ano"))

df[,i_CodIBGE := as.numeric(i_CodIBGE)]



rm(header_df)
```

# Variáveis explicativas

## x1: Municípios com Transporte Público Intramunicipal

```{r}
#Levantando a base
x1 <- read_excel(here("Dados/Base_MUNIC_2020.xlsx"), sheet = "Transporte") %>% 
  data.table()

#Selecionando colunas de interesse
x1 <- x1[, .("i_CodIBGE" = CodMun, 
       UF, 
       Regiao,
       Faixa_pop,  
       "x1_Transporte_Publico" = Mtra19, 
       "x1_1TZ_Idosos" = Mtra201, 
       "x1_2TZ_Estudantes_Publica" = Mtra202,
       "x1_3TZ_Estudantes_Privada" = Mtra203,
       "x1_4TZ_Carteiros" = Mtra204, 
       "x1_5TZ_PCD" = Mtra205, 
       "x1_6TZ_Policiais" = Mtra206, 
       "x1_7TZ_Professores" = Mtra207, 
       "x1_8TZ_Criancas" = Mtra208, 
       "x1_9TZ_Outros" = Mtra209, 
       "x1_10_TarifaZero_Todos" = Mtra2010)]

# Criando variáveis dummy
x1_cols <- grep("^x1", names(x1), value = TRUE)

x1[, (x1_cols) := lapply(.SD, function(x) {
  fifelse(x == "Sim", 1L,
  fifelse(x == "Não", 0L, NA_integer_))
}), .SDcols = x1_cols]

#Separando dados dos municípios
info_munic <- x1[, .(i_CodIBGE, UF, Regiao, Faixa_pop)]

#Adicionando ano:
x1[, "t_Ano" := 2020]

#Juntando à base principal:
df <- merge(df, info_munic, by = c("i_CodIBGE"), all = T)
df <- merge(df, x1, by = c("i_CodIBGE", "t_Ano", "UF", "Regiao", "Faixa_pop"), all = T)


rm(x1_cols, info_munic, x1)
```

## x2: Tarifa Zero

```{r}
#Variável X2: Cidades com Tarifa Zero
x2 <- all_data$`cidades com tarifa zero universal no Brasil - 2025` %>% 
  data.table()

#Alterando nome das colunas
setnames(x2, c("Código IBGE", "Início", "Tipo"), 
         c("i_CodIBGE", "x2t1_Ano_TZ", "x2t2_Tipo_TZ"))


#Corrigindo coluna de ano de implementação
x2[, x2t1_Ano_TZ := as.integer(x2t1_Ano_TZ)]

#Removendo colunas que não tem tarifa zero de ônibus:
x2 <- x2[x2t2_Tipo_TZ == "Ônibus"]

#Selecionando colunas de interesse:
x2 <- x2[, .(i_CodIBGE, x2t1_Ano_TZ)]

#Juntando à df
df <- merge(df, x2, by = "i_CodIBGE", all = T)

#Adicionando coluna dummy para presença de Tarifa Zero:
df <- df[, x2_TarifaZero := fifelse(t_Ano < x2t1_Ano_TZ | is.na(x2t1_Ano_TZ), 0,1)]


rm(x2)
```

# Variáveis Resposta

## y1: Emissão de Gases de Efeito Estufa

```{r}
y1 <- read_excel(here("Dados/Dados municipais resumido - CO2e GWP-AR5 v12.0.xlsx"), sheet = "Dados") %>% 
  data.table()


#Selecionando colunas de interesse
cols_to_drop <- c(
  "Setor de emissão",
  "Emissão/Remoção/Bunker",
  "Categoria emissora",
  "Sub-categoria emissora",
  "Recorte",
  "Estado",
  "Município")

y1 <- y1[, !..cols_to_drop]

#Pivotando as colunas de Anos
y1 <- melt(
  y1,
  id.vars = c("Atividade geral", "ID Território"),
  variable.name = "t_Ano",
  value.name = "y1_Emissoes_GEE")


#Sumarizando por grupos:
y1 <- y1[, .(
  y1_Emissoes_GEE = sum(y1_Emissoes_GEE, na.rm = TRUE)
), by = .(`Atividade geral`, `ID Território`, t_Ano)]

saveRDS(y1, here("DadosTratados/y1_EmissoesGEETratado.RDS"))

rm(cols_to_drop)
```

```{r}

#y1 <- readRDS(here("DadosTratados/y1_EmissoesGEETratado.RDS"))

#Selecionando dados de transporte:
y1 <- y1[,`Atividade geral` := fifelse(`Atividade geral` == "Transporte de passageiros", `Atividade geral`, "Outros")]


#Sumarizando por grupos:
y1 <- y1[, .(
  y1_Emissoes_GEE = sum(y1_Emissoes_GEE, na.rm = TRUE)
), by = .(`Atividade geral`, `ID Território`, t_Ano)]


#Separando os tipos de emissão em diferentes colunas

y1 <- dcast(y1,
  `ID Território` + t_Ano ~ `Atividade geral`,
  value.var = "y1_Emissoes_GEE")

#Renomeando e ajustando o Código IBGE:
y1 <- y1[, .("i_CodIBGE" = substr(as.character(`ID Território`), 2, nchar(as.character(`ID Território`))),
       t_Ano, 
       "y1_1EGEE_Transporte" = `Transporte de passageiros`, 
       "y1_2EGEE_Outros" = Outros)]

#Substituindo NA por 0
y1 <- y1[, lapply(.SD, function(x) ifelse(is.na(x), 0, x)), keyby = c("i_CodIBGE", "t_Ano")]

#Criando coluna com total de emissões
y1[, "y1_3SaldoTotal_EGEE" := sum(y1_1EGEE_Transporte, y1_2EGEE_Outros), by = c("i_CodIBGE", "t_Ano")]

y1[, t_Ano := as.numeric(as.character(t_Ano))]
y1[, i_CodIBGE := as.numeric(as.character(i_CodIBGE))]

#Substituindo 0 por NA
y1 <- y1[, lapply(.SD, function(x) fifelse(x == 0, NA, x)), keyby = c("i_CodIBGE", "t_Ano")]

#Juntando à base original
df <- merge(df, y1, by = c("i_CodIBGE", "t_Ano"), all.x =T)


#Salvando a base atualizada

saveRDS(y1, here("DadosTratados/y1.RDS"))

#Removendo a base y1
rm(y1)

```

## yZ: Qualidade do ar:

```{r}

#Juntando as bases
'y2_1 <- all_data$`Dados_monitorar_jan_mar_22-11-2022 DQAA`
y2_2 <- all_data$`Dados_monitorar_abr_jun_22-11-2022 DQAA`
y2_3 <- all_data$`Dados_monitorar_jul_nov_22-11-2022 DQAA`

y2 <- bind_rows(y2_1, y2_2) %>% 
  bind_rows(y2_3) %>% 
  data.table()

rm(y2_1, y2_2, y2_3)'
```

```{r}
'length(unique(y2$Nome.do.Município))
#Limpando os dados: 
y2 <- y2[, .(Nome.do.Município, Estado, Sigla, , Data, Hora)]

y2 <- dcast(
  y2,
  Nome.do.Município + Estado + Data + Hora ~ Sigla,
  value.var = "iqar",
  sep = "_iqar")
'
```

## y2: PIB per capita

```{r}

#Levantando a base
y2 <- read.csv(here("Dados/br_ibge_pib_municipio.csv"))

names(y2)
y2 <- y2 %>% 
  rename(i_CodIBGE = id_municipio,
    t_Ano = ano,
    y3_1PIBtotal = pib,
    y3_21VA_Total = va,
    y3_22VA_Agro = va_agropecuaria,
    y3_23VA_Industria = va_industria, 
    y3_24VA_Servicos = va_servicos,
    y3_25VA_SetorPublico = va_adespss, 
    y3_3impostos_liquidos = impostos_liquidos) %>% 
  data.table()


df <- merge(df, y2, by = c("i_CodIBGE", "t_Ano"), all.x = T)

rm(y2)

```

# Variáveis de Controle
## z1: População
```{r}
#Levantando a base

z1_1 <- read_xlsx(here("Dados/tabela4709.xlsx"), skip = 2) %>% 
  data.table()

z1_2 <- read_xlsx(here("Dados/tabela6579.xlsx"), skip = 2) %>%
  data.table()

#Renomeando colunas de z1_2:
z1_2 <- z1_2[, .(i_CodIBGE = as.numeric(`Cód.`),
         "2013" = Ano,
         "2014" = ...5, 
         "2015" = ...6, 
         "2016" = ...7,
         "2017" = ...8,
         "2018" = ...9, 
         "2019" = ...10, 
         "2020" = ...11, 
         "2021" = ...12, 
         "2024" = ...13)]

#Pivot_longer dos anos
z1_2 <- melt(z1_2, id.vars = "i_CodIBGE", variable.name = "t_Ano", value.name = "z1_Populacao")

z1_2[, t_Ano := as.numeric(as.character(t_Ano))]

#Tratando z1_1:
z1_1 <- z1_1[, .(i_CodIBGE = as.numeric(`Cód.`),
         "z1_Populacao" = Ano,
         "t_Ano" = 2022)]

z1 <- bind_rows(z1_1, z1_2)

df <- merge(df, z1, by = c("i_CodIBGE", "t_Ano"), all.x = T) 

df[, z1_Populacao := as.numeric(z1_Populacao)]

rm(z1, z1_1, z1_2)
```

### Adicionando o PIB per capita:
```{r}
df[, y3_PIBperCap := y3_1PIBtotal / z1_Populacao]

```

## z2: Área e Densidade Populacional
```{r}

# Lendo arquivos:
area_files <- list.files(here("Dados/IBGE_Area_Municipios/"), pattern = "\\.xls[x]?$", full.names = TRUE)

area_data <- lapply(area_files, read_excel)
#Adicionando nomes
names(area_data) <- area_files %>%
  basename() %>%
  file_path_sans_ext()


```

```{r}
#Limpando manualmente
#2010
z2 <- area_data$Areas_MU_UF_RE_BR %>% 
  data.table()

z2 <- z2[, .(i_CodIBGE = as.numeric(GEOCODIGO),
          t_Ano = 2010,
          z2_1AreaMun = as.numeric(AR_MUN_2010))]

#2013
z2_ano <- area_data$Areas_BR_RG_UF_MUN_2013 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GEOCODIGO),
          t_Ano = 2013,
          z2_1AreaMun = as.numeric(AREA_2013_KM2))]

z2 <- bind_rows(z2, z2_ano)

#2014
z2_ano <- area_data$Areas_MU_UF_RE_BR_2014 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2014,
          z2_1AreaMun = as.numeric(AR_MUN_2014))]

z2 <- bind_rows(z2, z2_ano)

#2015

z2_ano <- area_data$AR_BR_RG_UF_MUN_2015 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2015,
          z2_1AreaMun = as.numeric(AR_MUN_2015))]

z2 <- bind_rows(z2, z2_ano)


#2016

z2_ano <- area_data$AR_BR_RG_UF_MUN_2016 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2016,
          z2_1AreaMun = as.numeric(AR_MUN_2016))]

z2 <- bind_rows(z2, z2_ano)

#2017

z2_ano <- area_data$AR_BR_RG_UF_MES_MIC_MUN_2017 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2017,
          z2_1AreaMun = as.numeric(AR_MUN_2017))]

z2 <- bind_rows(z2, z2_ano)


#2018

z2_ano <- area_data$AR_BR_RG_UF_MES_MIC_MUN_2018 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2018,
          z2_1AreaMun = as.numeric(AR_MUN_2018))]

z2 <- bind_rows(z2, z2_ano)

#2019

z2_ano <- area_data$AR_BR_RG_UF_RGINT_RGIM_MES_MIC_MUN_2019 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2019,
          z2_1AreaMun = as.numeric(AR_MUN_2019))]

z2 <- bind_rows(z2, z2_ano)

#2020

z2_ano <- area_data$AR_BR_RG_UF_RGINT_RGIM_MES_MIC_MUN_2020 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_GCMUN),
          t_Ano = 2020,
          z2_1AreaMun = as.numeric(AR_MUN_2020))]

z2 <- bind_rows(z2, z2_ano)

#2021

z2_ano <- area_data$AR_BR_RG_UF_RGINT_RGIM_MES_MIC_MUN_2021 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_MUN),
          t_Ano = 2021,
          z2_1AreaMun = as.numeric(AR_MUN_2021))]

z2 <- bind_rows(z2, z2_ano)

#2022

z2_ano <- area_data$AR_BR_RG_UF_RGINT_MES_MIC_MUN_2022 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_MUN),
          t_Ano = 2022,
          z2_1AreaMun = as.numeric(AR_MUN_2022))]

z2 <- bind_rows(z2, z2_ano)

#2023

z2_ano <- area_data$AR_BR_RG_UF_RGINT_RGI_MUN_2023 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_MUN),
          t_Ano = 2023,
          z2_1AreaMun = as.numeric(AR_MUN_2023))]

z2 <- bind_rows(z2, z2_ano)

#2024

z2_ano <- area_data$AR_BR_RG_UF_RGINT_RGI_MUN_2024 %>% 
  data.table()

z2_ano <- z2_ano[, .(i_CodIBGE = as.numeric(CD_MUN),
          t_Ano = 2024,
          z2_1AreaMun = as.numeric(AR_MUN_2024))]

z2 <- bind_rows(z2, z2_ano)

rm(z2_ano, area_data, area_files)

```

```{r}
#Juntando à base principal

df <- merge(df, z2, by = c("i_CodIBGE", "t_Ano"), all.x = T)

df[ , z2_2DensidadeDemografica := z1_Populacao / z2_1AreaMun]


rm(z2)
```

# Reordenando colunas
```{r}
# Identificando colunas das variáveis
xyz_cols <- grep("^[xyz]", names(df), value = TRUE)

# Ordenando colunas alfabeticamente
xyz_cols <- sort(xyz_cols)

# Selecionando outras colunas
demais_cols <- setdiff(names(df), xyz_cols)

# Reorderando as colunas
setcolorder(df, c(demais_cols, xyz_cols))

rm(xyz_cols, demais_cols)

saveRDS(df, here("DadosTratados/df.RDS"))


```

